name: BackEnd-CICD

on:
  push:
    branches:  
      - "main"
      
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Grant execute permisson for gradlew
        run: chmod +x gradlew
        working-directory: quiz/quiz/
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew build
        working-directory: quiz/quiz/

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permisson for gradlew
        run: chmod +x gradlew
        working-directory: quiz/quiz/

      - name: Build with Gradle (without Test)
        run: ./gradlew build
        working-directory: quiz/quiz/
        
      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Hub build & push
        run: |
          docker build -t ${{ secrets.DOCKER_NICKNAME }}/${{ secrets.DOCKER_BE_REPO }} .
          docker images
          docker push ${{ secrets.DOCKER_NICKNAME }}/${{ secrets.DOCKER_BE_REPO }}
        working-directory: quiz/quiz/

      - name: Deploy to Prod WAS Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WAS_HOST }}
          username: ${{ secrets.WAS_USERNAME }}
          key: ${{ secrets.WAS_KEY }}
          port: ${{ secrets.WAS_SSH_PORT }}
          script: |
            cd /home/ubuntu/
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sudo docker rm -f $(sudo docker ps -qa)
            sudo docker pull ${{ secrets.DOCKER_NICKNAME }}/${{ secrets.DOCKER_BE_REPO }}
            sudo docker-compose up -d
            sudo docker image prune -f
